"""
==========================================================
ResIoT Simulator

Module 7 : environment.py

Author : Kaneez Fizza

Description
-----------
Simulates an IoT environment in which faults occur and are
handled by the Functional Agents.

==========================================================
"""

import random
from typing import Dict, List
import pandas as pd

from failures import FaultGenerator
from orchestrator import Orchestrator, RecoveryPlan
from agents import (
    AS1SensingAgent,
    AS2TransmissionAgent,
    AS3AnalyticsAgent,
    AS4InformationAgent,
    AS5ActuationAgent,
)
from knowledge_base import KnowledgeBase
from config import RECOVERY_STRATEGIES

from fault_model import (
    get_fault_profile,
    simulate_detection,
    simulate_recovery,
    success_probability,
    communication_cost
)


class Environment:

    def __init__(self):

        self.kb = KnowledgeBase()
        self.kb.register_fault(
            "SENSOR_DRIFT",
            [
                "FastCalibration",
                "RedundantSensor",
                "SensorReset"
            ]
        )

        self.kb.register_fault(
            "COMM_LOSS",
            [
                "DynamicRouting",
                "GatewayRestart",
                "BackupLink"
            ]
        )

        self.kb.register_fault(
            "ACTUATOR_FAULT",
            [
                "LocalRecalibration",
                "RetryAction",
                "FallbackMode"
            ]
        )

        # ---------------------------------------------------
        # Register recovery strategies in KB
        # ---------------------------------------------------

        for fault, strategies in RECOVERY_STRATEGIES.items():
            self.kb.register_fault(
                fault,
                strategies
            )

        # ---------------------------------------------------
        # Functional Agents
        # ---------------------------------------------------

        self.as1 = AS1SensingAgent(self.kb)
        self.as2 = AS2TransmissionAgent(self.kb)
        self.as3 = AS3AnalyticsAgent(self.kb)
        self.as4 = AS4InformationAgent(self.kb)
        self.as5 = AS5ActuationAgent(self.kb)

        self.agents = {

            "AS1": self.as1,

            "AS2": self.as2,

            "AS3": self.as3,

            "AS4": self.as4,

            "AS5": self.as5

        }

        self.orchestrator = Orchestrator()
        # ==========================================
        # Simulation Metrics
        # ==========================================

        self.total_messages = 0

        self.total_detection_time = 0

        self.total_recovery_time = 0

        self.completed_faults = 0

        self.communication_history = []

        self.performance_history = []


    # ======================================================
    # Select Responsible Agent
    # ======================================================

    def responsible_agent(self, stage):

        if stage == "AS1":
            return self.as1

        if stage == "AS2":
            return self.as2

        if stage == "AS3":
            return self.as3

        if stage == "AS4":
            return self.as4

        return self.as5

    # ======================================================
    # One Simulation Episode
    # ======================================================

    # ======================================================
    # One Simulation Episode
    # ======================================================

    def step(self, fault):
        """
        Executes one simulation episode using the supplied fault.

        The fault is generated by SimulationScenario so that
        ResIoT, Rule-Based and ML-Based systems all receive
        the exact same fault sequence.
        """

        # -----------------------------------------
        # Determine responsible agent
        # -----------------------------------------

        agent = self.responsible_agent(fault.stage)

        # -----------------------------------------
        # Perceive
        # -----------------------------------------

        perceived = agent.perceive(fault)

        # -----------------------------------------
        # Reason
        # -----------------------------------------

        policy = agent.reason(perceived)

        # -----------------------------------------
        # Plan
        # -----------------------------------------

        plan = agent.plan(policy)

        # -----------------------------------------
        # Send plan to Orchestrator
        # -----------------------------------------

        recovery_plan = RecoveryPlan(

            sender=agent.name,

            fault_type=fault.name,

            strategy=plan["strategy"],

            confidence=plan["confidence"],

            priority=fault.severity

        )

        self.orchestrator.receive_plan(recovery_plan)

        approved = self.orchestrator.resolve_conflicts()

        # -----------------------------------------
        # Physics-based Simulation
        # -----------------------------------------

        profile = get_fault_profile(fault.name)

        mttd = simulate_detection(profile, "ResIoT")

        mttr = simulate_recovery(profile, "ResIoT")

        probability = success_probability(profile, "ResIoT")

        messages = communication_cost(profile, "ResIoT")

        success = random.random() < probability

        # -----------------------------------------
        # Update Metrics
        # -----------------------------------------

        self.total_detection_time += mttd
        self.total_recovery_time += mttr
        self.total_messages += messages
        self.completed_faults += 1

        self.communication_history.append(messages)

        self.performance_history.append({
            "Episode": self.completed_faults,
            "MTTD": mttd,
            "MTTR": mttr,
            "Messages": messages,
            "Success": success,
            "Confidence": policy.confidence
        })

        # -----------------------------------------
        # Learning
        # -----------------------------------------

        agent.learn(
            perceived,
            policy,
            success,
            mttr
        )

        # -----------------------------------------
        # Return Episode Results
        # -----------------------------------------

        return {
            "fault": fault.name,
            "stage": fault.stage,
            "agent": agent.name,
            "strategy": policy.strategy,
            "success": success,
            "mttd": mttd,
            "mttr": mttr,
            "messages": messages,
            "confidence": policy.confidence
        }



    # ======================================================
    # Run Multiple Episodes
    # ======================================================

    def run(self, scenario):

        """
        Runs a complete SimulationScenario.
        """

        history = []

        for event in scenario:
            history.append(

                self.step(event.fault)

            )

        return history

    # ======================================================
    # Statistics
    # ======================================================

    def statistics(self):

        average_mttd = (
            self.total_detection_time / self.completed_faults
            if self.completed_faults else 0
        )

        average_mttr = (
            self.total_recovery_time / self.completed_faults
            if self.completed_faults else 0
        )

        return {

            "Metrics": {

                "Mean MTTD": average_mttd,

                "Mean MTTR": average_mttr,

                "Success Rate":
                    self.as1.statistics()["success_rate"]

            },

            "Communication": {

                "Messages": self.total_messages,

                "Average Messages":
                    self.total_messages / max(1, self.completed_faults)

            },

            "Knowledge Base":
                self.kb.statistics(),

            "Orchestrator":
                self.orchestrator.statistics()

        }

# ==========================================================
# Test
# ==========================================================

if __name__ == "__main__":

    env = Environment()

    results = env.run(20)

    print()

    print("Simulation Results")

    print("-" * 60)

    for r in results:

        print(r)

    print()

    print("Environment Statistics")

    print("-" * 60)

    print(env.statistics())